import re

# replace certain string to match grid
INST_ABBR = {
    "virginia technology": "virginia tech",
    "nanyang technology university": "nanyang technological university",
    "technology univeristy munchen": "technical university of munich",
    'ucla': 'university of california los angeles',
    'ucsd': 'university of california san diego',
    "ucsf": "university of california san francisco",
    "ucsb": "university of california santa barbara",
    "university of california at berkeley": "university of california berkeley",
    "university of california at los angeles": "university of california los angeles",
    "university of california at san francisco": "university of california san francisco",
    "university of california at santa barbara": "university of california santa barbara",
    "university of california at irvine": "university of california irvine",
    "university of california at san diego": "university of california san diego",
    "university of california at davis": "university of california davis",
    "university of california at santa cruz": "university of california santa cruz",
    "california university berkeley": "university of california berkeley",
    "california university los angeles": "university of california los angeles",
    "california university san francisco": "university of california san francisco",
    "california university santa barbara": "university of california santa barbara",
    "california university irvine": "university of california irvine",
    "california university san diego": "university of california san diego",
    "california university davis": "university of california davis",
    "california university santa cruz": "university of california santa cruz",
    'caltech': 'california institute of technology',
    "wisconsin university madison": "university of wisconsin madison",
    'ccny': 'city college of new york',
    'cmu': 'carnegie mellon university',
    'georgia tech': 'georgia institute of technology',
    'penn state': 'pennsylvania state university',
    'umass': 'university of massachusetts amherst',
    "massachusetts university amherst": "university of massachusetts amherst",
    'cuny': 'city university of new york',
    'harvard school of': 'harvard university school of',
    "nyu": "new york university",
    "suny": "state university of new york",
    "university of michigan": "university of michigan ann arbor",
    "michigan university ann arbor": "university of michigan ann arbor",
    "carnegie institution": "carnegie institution for science",
    "johns hopkins": "johns hopkins university",
    "usda": "united states department of agriculture",
    "ohio state university": "the ohio state university",
    "oregon health sciences": "oregon health and science university",
    "oregon health and sciences university": "oregon health and science university",
    "oregon health and science university": "oregon health and science university",
    "washington university": "washington university in st louis",
    "rutgers": "rutgers the state university of new jersey",
    "va medical center": "veterans health administration",
    "weill cornell": "cornell university",
    "beth israel": "beth israel deaconess medical center",
    "mayo": "mayo clinic",
    "anderson cancer center": "the university of texas md anderson cancer center",
    "dartmouth": "dartmouth college",
    "medical college of pennsylvania": "drexel university",
    "centers for disease control": "centers for disease control and prevention",
    "albany medical college": "albany medical center hospital",
    "medical college of ohio": "university of toledo medical center",
    "jefferson medical college": "thomas jefferson university",
    "medical college of virginia": "virginia commonwealth university",
    "virginia polytechnic": "virginia tech",
    "virginia university charlottesville": "university of virginia",
    "case western": "case western reserve university",
    "uniformed services university for the health sciences": "united states department of defense",
    "wake forest": "wake forest university",
    "salk institute": "salk institute for biological studies",
    "children s national medical center": "children s national health system",
    "chapel hill": "university of north carolina at chapel hill",
    "lilly corporate center": "eli lilly",
    "national heart, lung, and blood institute": "national institutes of health",
    "national heart, and blood institute": "national institutes of health",
    "new york state psychiatric institute": "newyork presbyterian hospital",
    "new england medical center": "tufts medical center",
    "sloan kettering institute": "memorial sloan kettering cancer center",
    "institute for allergy and asthma": "national institutes of health",
    "forsyth institute": "harvard university",
    "california institute technology": "california institute of technology",
    "robert wood johnson": "rutgers the state university of new jersey",
    "university at buffalo": "university at buffalo, state university of new york",
    "university at albany": "university at buffalo, state university of new york",
    "columbia presbyterian": "columbia university",
    "john hopkins": "johns hopkins university",
    "va hospital": "veterans health administration",
    "baylor college": "baylor college of medicine",
    "food and drug administration": "united states food and drug administration",
    "columbia college": "columbia university",
    "college of william and mary": "william and mary",
    "college of physicians and surgeons": "columbia university",
    "la jolla institute": "la jolla institute for allergy and immunology",
    "smithkline beecham": "glaxosmithkline",
    "albert einstein medical center": "einstein medical center philadelphia",
    "joslin diabetes center": "harvard university",
    "national jewish center": "national jewish health",
    "brown medical": "brown university",
    "hospital cornell": "cornell university",
    "wilford hall": "united states department of defense",
    "bowman gray": "wake forest university",
    "brigham and women": "brigham and women's hospital",
    "loyola": "loyola university chicago",
    "uniformed service": "united states department of defense ",
    "hahnemann university": "hahnemann university hospital",
    "burnham institute": "sanford burnham prebys medical discovery institute",
    "lsu ": "louisiana state university ",
    "kennedy institute": "kennedy kreiger institute",
    "providence heart and vascular institute": "providence st vincent medical center",
    "virginia institute of marine science": "william and mary",
    "ochsner": "ochsner medical center",
    "the state university of new jersey": "rutgers the state university of new jersey",
    "new jersey medical school": "rutgers the state university of new jersey",
    "cold spring": "cold spring harbor laboratory",
    "university of medicine and dentistry of new jersey": "rutgers the state university of new jersey",
    "schering plough": "msd",
    "wistar": "the wistar institute",
    "michigam": "michigan",
    "genentech": "roche",
    "childrens hospital los angeles": "children's hospital of los angeles",
    "parke davis": "pfizer",
    "shriners": "shriners hospitals for children galveston",
    "albany medical": "albany medical center hospital",
    "albany college of pharmacy": "albany college of pharmacy and health sciences",
    "research triangle institute": "rti international",
    "cedars sinai heart institute": "cedars sinai medical center",
    "allegheny university of the health sciences": "drexel university",
    "national jewish medical and research center": "national jewish health",
    "rosalind franklin university": "rosalind franklin university of medicine and science",
    "cephalon": "teva pharmaceuticals",
    "cetus": "novartis",
    "pharmacia corporation": "pfizer",
    " genentech ": " roche ",
    "merck": "msd",
    "air force research laboratory": "united states air force research laboratory",
    "air force research labs": "united states air force research laboratory",
    "air force research lab": "united states air force research laboratory",
    "army research laboratory": "united states army research laboratory",
    "army research labs": "united states army research laboratory",
    "army research lab": "united states army research laboratory",
    "army engineering university": "pla army engineering university",
    "epfl": "swiss federal institute of technology in lausanne",
    "national chiao tung university": "national yang ming chiao tung university",
    "technion": "technion israel institute of technology",
    "csiro": "commonwealth scientific and industrial research organisation",
    "wroclaw university of technology": "wroclaw university of science and technology",
    "wrocław university of science and technology": "wroclaw university of science and technology",
    "helsinki university of technology": "aalto university",
    "inria": "french institute for research in computer science and automation",
    "university of rome la sapienza": "sapienza university of rome",
    "universita di roma la sapienza": "sapienza university of rome",
    "academy sinica": "academia sinica",
    "brunel university": "brunel university london",
    "tijuana institute of technology": "instituto tecnologico de tijuana",
    "kaist": "korea advanced institute of science and technology",
    "university politehnica of bucharest": "polytechnic university of bucharest",
    "imperial college": "imperial college london",
    "dresden university of technology": "tu dresden",
    "texas university austin": "the university of texas at austin",
    "johannes kepler university": "johannes kepler university of linz",
    "illinois university urbana": "university of illinois urbana champaign",
    "university of illinois at urbana champaig": "university of illinois urbana champaign",
    "universityof cyprus": "university of cyprus",
    "isti cnr": "institute of information science and technologies",
    "cnr isti": "institute of information science and technologies",
    "universitat karlsruhe": "karlsruhe institute of technology",
    "universita di torino": "university of turin",
    "washington university seattle": "university of washington",
    "toronto university": "university of toronto",
    "university of padova": "university of padua",
    "shanghai jiaotong university": "shanghai jiao tong university",
    "bell laboratories": "nokia",
    "bell laboratory": "nokia",
    "bell labs": "nokia",
    "bell lab": "nokia",
    "cern": "european organization for nuclear research",
    "queens university kingston": "queens college at kingston",
    "university of magdeburg": "otto von guericke university magdeburg",
    "universitat dortmund": "tu dortmund university",
    "university of dortmund": "tu dortmund university",
    "tu dortmund": "tu dortmund university",
    "universitat erlangen nurnberg": "university of erlangen nuremberg",
    "ludwig maximilian university of munich": "ludwig maximilians universitat munchen",
    "vu university": "vu amsterdam",
    "universitat tubingen": "university of tubingen",
    "chinese academy of science": "chinese academy of sciences",
    "adobe": "adobe systems",
    " unsw ": "unsw sydney",
    "microsoft china": "microsoft research asia",
    "harvard medical school": "harvard university",
    "information trust institute": "university of illinois urbana champaign",
    "microsoft research beijing": "microsoft research asia",
    "laas": "laboratory for analysis and architecture of systems",
    "hp laboratories": "hewlett packard",
    "hp laboratory": "hewlett packard",
    "hp labs": "hewlett packard",
    "hp lab": "hewlett packard",
    "universita di salerno": "university of salerno",
    "irisa": "institut de recherche en informatique et systemes aleatoires",
    "darmstadt university of technology": "tu darmstadt",
    "texas technology": "texas tech",
    "k u leuven": "ku leuven",
    "university of electron science and technology": "university of electronic science and technology of china",
    "huawei": "huawei technologies",
    "university politecnica de catalunya": "universitat politecnica de catalunya",
    "german cancer research ctr": "german cancer research center",
    "university carlos iii of madrid": "carlos iii university of madrid",
    "universita di milano": "university of milan",
    "universitat wurzburg": "julius maximilians university of wurzburg",
    "tsmc": "taiwan semiconductor manufacturing company",
    "los alamos national labs": "laboratorio nacional de los alamos",
    "lmu munich": "ludwig maximilians universitat in munich",
    "german research center for artificial intelligence": "german research centre for artificial intelligence",
    "mpi informatik": "max planck institute for informatics",
    "swiss federal institute of technology zurich": "swiss federal institute of technology in zurich",
    "ntnu": "norwegian university of science and technology",
    "aachen university of technology": "rwth aachen university",
    "academy of sciences of the czech republic": "czech academy of sciences",
    "petersburg state university": "st petersburg university",
    "university of torino": "university of turin",
    "technical university berlin": "technical university of berlin",
    "fraunhofer heinrich hertz institute": "fraunhofer institute for telecommunications heinrich hertz institute",
    "university of jena": "friedrich schiller university jena",
    "technology university dresden": "tu dresden",
    "dublin institute of technology": "tu dublin",
    "nebraska university lincoln": "university of nebraska lincoln",
    "icar cnr": "institute for high performance computing and networking",
    "ind technology research institute": "industrial technology research institute",
    "ben gurion university": "ben gurion university of the negev",
    "politec di milano": "polytechnic university of milan",
    "anna university": "anna university chennai",
    "rensselaer polytech institute": "rensselaer polytechnic institute",
    "pacific northwest national lab ": "pacific northwest national laboratory ",
    "national institute of inf tokyo": "national institute of information and communications technology",
    "electron and telecommunications research institute": "electronics and telecommunications research institute",
    "university of lugano": "universita della svizzera italiana",
    "humboldt university of berlin": "humboldt universitat zu berlin",
    "university of genova": "university of genoa",
    "universita di genova": "university of genoa",
    "inesc id": "instituto de engenharia de sistemas e computadores investigacao e desenvolvimento",
    "vit university": "vellore institute of technology university",
    "czech technical university": "czech technical university in prague",
    "hong kong polytech university": "hong kong polytechnic university",
    "etri": "electronics and telecommunications research institute",
    "national institute of stand and technology": "national institute of standards and technology",
    "open university of the netherlands": "open university in the netherlands",
    "politecnico di milano": "polytechnic university of milan",
    "cnrs": "french national centre for scientific research",
    "bbn technologies": "raytheon technologies research center",
    "oak ridge national lab ": "oak ridge national laboratory ",
    "charles iii university": "carlos iii university of madrid",
    "iiit delhi": "indraprastha institute of information technology delhi",
    "naval research laboratory": "united states naval research laboratory",
    "instituto superior tecnico": "university of lisbon",
    "tu munchen": "technical university of munich",
    "institute of autom ": "institute of automation ",
    "nicta": "national ict australia",
    "institute of comput technology": "institute of computing technology",
    "hebrew university": "hebrew university of jerusalem",
    "arizona university tucson": "university of arizona",
    "iowa university iowa city": "university of iowa",
    "victoria university bc canada": "university of victoria",
    "university of koblenz landau": "university of koblenz and landau",
    "illinois university chicago": "university of illinois at chicago",
    "british columbia university vancouver": "university of british columbia",
    "southampton university uk": "university of southampton",
    "calgary university alta": "university of calgary",
    "university of osnabruck": "osnabruck university",
    "ibm china": "ibm research china",
    "pittsburgh university pa": "university of pittsburgh",
    "ottawa university ont canada": "university of ottawa",
    "universita di firenze": "university of florence",
    "universitat kaiserslautern": "university of kaiserslautern",
    "university medical ctr utrecht netherlands": "universitair medisch centrum utrecht",
    "technical university of catalonia": "polytechnic university of catalonia",
    "fzi research center for information technology": "forschungszentrum informatik",
    "universitat bonn": "university of bonn",
    "radboud university": "radboud university nijmegen",
    "slovak university of technology": "slovak university of technology in bratislava",
    "barcelona supercomput center": "barcelona supercomputing center",
    "northwestern polytech university": "northwestern polytechnic university",
    "dfki gmbh": "deutsches forschungszentrum fur kunstliche intelligenz",
    "argonne national laboratory": "argonne national laboratory",
    "argonne national lab": "argonne national laboratory",
    "athens university of econ and business": "athens university of economic and business",
    "pixar animation studios": "walt disney",
    "vrije universiteit": "vu amsterdam",
}

# specify certain organization names with country information
MANUAL_ADDED = (
    ("Germany", "ulm university", "University of Ulm"),
    ("Australia", "university of newcastle", "University of Newcastle Australia"),
    ("Netherlands", "cwi", "Centrum Wiskunde & Informatica"),
    ("Japan", "tokyo university", "University of Tokyo"),
    ("Poland", "warsaw university", "University of Warsaw"),
    ("Germany", "university of leipzig", "Leipzig University"),
    ("Finland", "university of tampere", "Tampere University"),
    ("Germany", "university of heidelberg", "Heidelberg University"),
    ("Germany", "paderborn university", "University of Paderborn"),
    ("Germany", "university of karlsruhe", "Karlsruhe Institute of Technology"),
    ("Tunisia", "university of tunis", "Tunis University"),
    ("Canada", "waterloo university", "University of Waterloo"),
    ("Canada", "alberta university", "University of Alberta"),
    ("United Kingdom", "ulster university", "University of Ulster"),
    ("Germany", "university of kiel", "Kiel University"),
    ("Denmark", "university of aarhus", "Aarhus University"),
    ("Germany", "university of marburg", "Philipp University of Marburg"),
    ("Canada", "british columbia university", "University of British Columbia"),
    ("United Kingdom", "plymouth university", "University of Plymouth"),
    ("United States", "wisconsin university", "University of Wisconsin System"),
    ("United States", "southern illinois university", "Southern Illinois University System"),
    ("United States", "minnesota university", "University of Minnesota"),
    ("United States", "university of california", "University of California System"),
    ("United States", "nasa", "National Aeronautics and Space Administration"),
    ("United States", "mit", "Massachusetts Institute of Technology"),
    ("United States", "university of maryland", "University System of Maryland"),
    ("United States", "maryland university", "University System of Maryland"),
    ("United States", "university of illinois", "University of Illinois System"),
    ("United States", "university of texas", "The University of Texas System"),
    ("United States", "university of north carolina", "University of North Carolina System"),
    ("United States", "university of wisconsin", "University of Wisconsin System"),
    ("United States", "purdue university", "Purdue University System"),
    ("United States", "university of colorado", "University of Colorado System"),
    ("United States", "mount sinai", "Mount Sinai Health System"),
    ("United States", "university of tennessee", "University of Tennessee System"),
    ("United States", "medical college of georgia", "University System of Georgia"),
    ("United States", "university of massachusetts", "University of Massachusetts System"),
    ("United States", "university of nebraska", "University of Nebraska System"),
    ("United States", "california state university", "California State University System"),
    ("United States", "university of nevada", "Nevada System of Higher Education"),
    ("United States", "university of hawaii", "University of Hawaii System"),
    ("United States", "university of hawai i", "University of Hawaii System"),
    ("United States", "university of arkansas", "University of Arkansas System"),
    ("United States", "texas a and m", "Texas A&M University System"),
    ("United States", "northeastern ohio", "University System of Ohio"),
    ("United States", "southern illinois university", "Southern Illinois University System"),
    ("United States", "us army", "United States Army"),
    ("United States", "u s army", "United States Army"),
    ("United States", "united states navy", "Navy League of the United States"),
    ("United States", "us navy", "Navy League of the United States"),
    ("United States", "u s navy", "Navy League of the United States"),
    ("United States", "florida university", "University of Florida"),
    ("Australia", "rmit", "RMIT University"),
    ("United States", "uiuc", "University of Illinois Urbana-Champaign"),
    ("South Korea", "postech", "Pohang University of Science and Technology")
)

#  remove ambiguous GRID names when the bracketed contents are stripped
AMBIGUOUS = [
    "software",
    "engineering",
    "faculty",
    "public Health",
    "electron",
    "heidelberg",
    "computer science department",
    "college of business administration",
    "university of technology",
    "research center for information technology",
    "institute of technology",
    "informatica",
    "search institute",
    "search lab",
    "graduate school of engineering",
    "centre for demographic studies",
    "heart hospital",
    "instituto",
    "innovation",
    "box",
    "ion engineering",
    "applied sciences",
    "applied mathematics",
    "del",
    "information technology university",
    "studi",
    "university hospital",
    "university school",
    "he university",
    "signal processing",
    "space",
    "engineering laboratory",
    "bell",
    "tech u",
    "team",
    "nice",
    "milan",
    "s and t",
    "s and n",
    "university of science and technology",
    "air",
    "university hospital and clinics",
    "graduate school",
    "university of science and technology",
    "public health",
    "research america",
    "world",
    "triangle",
    "ciudad",
    "action",
    "search",
    "traces",
    "progress",
    "concern"
]

COUNTRY = (
    ('italy', 'italia', 'torino', 'turin', 'portici', 'palermo', 'milano', 'genoa', 'naples', 'parma', 'catania',
     'napoli', 'modena', 'brescia', 'bologna', 'cagliari', 'verona', 'bari', 'pisa', 'pavia', 'terni', 'padova',
     'veruno', 'trieste', 'bari', 'florence', 'roma', 'rome', 'foggia'),
    ('united kingdom', 'u.k.', ' uk ', 'uk.', 'england', 'uk', 'liverpool', 'london', 'crumpsall', 'leicester',
     'manchester', 'cardiff', 'salford', 'bradford', 'oxford', 'clwyd', 'edinburgh', 'edinburge', 'scotland', 'leeds',
     'glasgow', 'bristol', 'uk'),
    ('united states', 'united states of america', 'u.s.a', 'u. s. a.', 'united states', 'massachusetts', 'boston',
     'howard university', 'torrance', 'san francisco', 'duarte', 'los alamos', 'houston', "usa", 'pittsburg',
     'los angeles', 'atlanta', 'new orleans', 'philadelphia', 'baltimore', 'colorado', 'california', 'michigan',
     'minnesota', 'iowa', 'baltimore',
     'maryland', 'florida', 'chicago', 'illinois', 'bethesda', 'atlanta', 'stanford', 'manhattan', 'yale',
     "minneapolis", "chapel hill", "detroit", "ann arbor", "nashville", "harvard", "portland"),
    ('germany', 'frg', 'brd', 'f.r.g.', 'deutschland', 'engelskirchen', 'berlin', 'hannover', 'marburg', 'mainz',
     'leipzig', 'frankfurt'),
    ('japan', 'keio University', 'jikei university', 'shiga university', 'jikei university',
     'niigata university', 'sendai city', 'shiba', 'asahikawa',
     'tokyo', 'yokohama', 'osaka', 'nagoya', 'sapporo', 'kobe', 'kyoto',
     'fukuoka', 'kawasaki', 'saitama', 'hiroshima', 'sendai', 'kitakyushu',
     'chiba', 'sakai', 'hamamatsu', 'niigata', 'shizuoka', 'okayama', 'asahikawa',
     'yamaguchi', 'okayama', 'gunma', 'hyogo', 'kanazawa', 'fukui', 'tajimi',
     'komagome', 'akita', 'suita', 'kochi', 'nara medical', 'keio', 'kobe university', 'gunma', 'gifu university',
     'toranomon', 'bunkyo gakuin', 'nagasaki', 'matsue', 'isehara', 'kagawa', 'toyama', 'kanagawa'),
    ('south korea', 'korea', 'seoul'),
    ('russia', 'moscow', 'st petersburg', 'vladivostok'),
    ('austria', 'linz', 'wien', ' graz', 'innsbruck'),
    ('israel', 'jerusalem', 'haifa', 'tel aviv'),
    ('norway', ' oslo'),
    ('finland', 'helsinki'),
    ('south africa', 'johannesburg'),
    ('france', 'paris', 'marseille', 'brest', 'limoges', 'toulouse', 'lyon', 'tours'),
    ('canada', 'vancouver', 'ontario', 'ottawa', 'nova scotia', 'calgary', 'alberta', 'toronto', 'ont',
     'winipeg', 'saskatchewan', 'halifax', 'kingston', 'hamilton', 'new brunswick', 'manitoba', 'prince edward island',
     'winnipeg'),
    ('denmark', 'copenhagen'),
    ('taiwan', 'taiwan, ', 'taipei', 'chi-mei medical'),
    ('china', 'beijing', 'pr china', 'hangzhou', 'zhejiang', 'shenyang', 'shanghai', 'guiyang', 'chengdu',
     'chongqing', 'wuhan',
     'guangzhou', 'shandong'),
    ('egypt', 'cairo'),
    ('poland', 'gdansk', 'krakow', 'bialystok', 'warszawie'),
    ('turkey', 'istanbul', ' ankara'),
    ('netherlands', 'utrecht', 'nijmegen', 'amsterdam', 'leiden', 'rotterdam'),
    ('belgium', 'belgique', ' namur', 'bruxelles', ' genk'),
    ('sweden', 'karlstad', 'uppsala', 'stockholm'),
    ('australia', ' perth', 'queensland', 'canberra', 'melbourne', 'brisbane'),
    ('south africa', 'johannesburg', 'onderstepoort', 'pretoria'),
    ('hungary', 'ungarn'),
    ('india', 'chandigarh', 'hyderabad', 'delhi', 'calcutta', 'wardha', ' ucms',
     'ludhiana', 'vellore'),
    ('ireland', 'dublin', 'belfast'),
    ('colombia', 'bogota'),
    ('spain', 'madrid', ' toledo', ' alicante', 'zaragoza', 'saragossa', 'barcelona',
     'hospital vega baja', 'valencia', 'malaga', 'espana', 'esapana'),
    ('greece', 'athens'),
    ('new zealand', 'upper hutt', 'auckland'),
    ('saudi arabia', 'riyadh'),
    ('nigeria', 'ibadan'),
    ('croatia', 'yugoslavia', 'belgrade'),
    ('switzerland', 'basel', ' geneva'),
    ('brazil', 'rio de janeiro'),
    ('thailand', 'bangkok'),
    ('argentina', 'buenos aires'),
    ('tunisia', 'tunis', 'tunisie'),
    ('czech republic', ' praha', 'prague', 'czechoslovakia'),
    ('hungary', 'budapest'),
    ('zimbabwe', 'bulawayo'),
    ('malaysia', 'kelantan'),
    ('vietnam', 'hanoi'),
    ('hong kong', 'hong kong'),
    (' iran', 'tehran', 'shiraz', 'mashhad'),
    ('brazil', 'brasil', 'rio de janeiro', 'cordeiropolis'),
    ('mexico', 'mexico city'),
    ('romania', 'bucharest'),
    ('congo', 'democratic republic of congo'),
    ('armenia', 'yerevan'),
    ('bosnia and herzegovina', 'bosnia', 'herzegovina'),
    ('albania', 'tirana'),
    ('tanzania', 'morogoro'),
    ('sri lanka', 'sri lanka'),
    ('cyprus', 'nicosia'),
    ('gambia', ' banjul'),
    ('lithuania', 'lietuvos'),
    ('peru', ' lima'),
    ('portugal', 'lisboa'),
    ('philippines', 'manila'),
    ('kuwait', 'kuwait city'),
    ("venezuela", 'caracas'),
    ('senegal', 'dakar'),
    ('jamaica', 'jamaica'),
    ('malawi', 'malawi'),
    ('new zealand', 'nz'),
    ('chile', 'santiago'),
    ('ethiopia', 'addis'),
    ('mozambique', 'maputo'),
    ('lebanon', 'beirut'),
    ('singapore', 'singapore'),
    ('pakistan', 'pakistan', 'karachi'),
    ('united arab emirates', 'uae'),
    ('ukraine', 'kyiv'),
    ('kenya', 'nairobi'),
    ('oman', 'muscat'),
    ('indonesia', 'jakarta'),
    ('ljubljana', 'slovenia'),
    ('norway', 'oslo'),
    ('morocco', 'maroc'),
    ('bulgaria', 'bulgaria'),
    ('bangladesh', 'dhaka'),
    ('cuba', 'cuba', 'camaguey'),
    ('switzerland', 'zurich'),
    ('slovak republic', 'slovakia'),
    ('uruguay', 'montevideo'),
    ('iceland', 'iceland'),
    ('uganda', 'uganda')
)

US_STATES = (
    'Alabama', 'Alaska', 'Arizona', 'Arkansas',
    'California', 'Colorado', 'Connecticut', 'Delaware', 'Florida',
    'Georgia', 'Hawaii', "Hawai'i", 'Idaho', 'Illinois', 'Indiana', 'Iowa',
    'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
    'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri',
    'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey',
    'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio',
    'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina',
    'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia',
    'Washington', 'West Virginia', 'Wisconsin', 'Wyoming', 'Washington DC',
    ' AL ', ' AK ', ' AZ ', ' AR ', ' CA ', ' CO ', ' CT ', ' DE ', ' FL ', ' GA ', ' HI ',
    ' ID ', ' IL ', ' IN ', ' IA ', ' KS ', ' KY ', ' LA ', ' ME ', ' MD ', ' MA ', ' MI ',
    ' MN ', ' MS ', ' MO ', ' MT ', ' NE ', ' NV ', ' NH ', ' NJ ', ' NM ', ' NY ', ' NC ',
    ' ND ', ' OH ', ' OK ', ' OR ', ' PA ', ' RI ', ' SC ', ' SD ', ' TN ', ' TX ', ' UT ',
    ' VT ', ' VA ', ' WA ', ' WV ', ' WI ', ' WY ', ' DC ',
    ' AL,', ' AK,', ' AZ,', ' AR,', ' CA,', ' CO,', ' CT,', ' DE,', ' FL,', ' GA,', ' HI,',
    ' ID,', ' IL,', ' IN,', ' IA,', ' KS,', ' KY,', ' LA,', ' ME,', ' MD,', ' MA,', ' MI,',
    ' MN,', ' MS,', ' MO,', ' MT,', ' NE,', ' NV,', ' NH,', ' NJ,', ' NM,', ' NY,', ' NC,',
    ' ND,', ' OH,', ' OK,', ' OR,', ' PA,', ' RI,', ' SC,', ' SD,', ' TN,', ' TX,', ' UT,',
    ' VT,', ' VA,', ' WA,', ' WV,', ' WI,', ' WY,', ' DC,',
    ' AL.', ' AK.', ' AZ.', ' AR.', ' CA.', ' CO.', ' CT.', ' DE.', ' FL.', ' GA.', ' HI.',
    ' ID.', ' IL.', ' IN.', ' IA.', ' KS.', ' KY.', ' LA.', ' ME.', ' MD.', ' MA.', ' MI.',
    ' MN.', ' MS.', ' MO.', ' MT.', ' NE.', ' NV.', ' NH.', ' NJ.', ' NM.', ' NY.', ' NC.',
    ' ND.', ' OH.', ' OK.', ' OR.', ' PA.', ' RI.', ' SC.', ' SD.', ' TN.', ' TX.', ' UT.',
    ' VT.', ' VA.', ' WA.', ' WV.', ' WI.', ' WY.', ' DC.'
)

# replace certain abbreviations
ABBR = {
    re.compile(r"\buniv\b\.|\buniv\b|\buni\b\.|\buni\b", re.I): " university ",
    re.compile(r"\btech\b\.|\btech\b|\bTechnol\b\.|\btechnol\b", re.I): "technology",
    re.compile(r"\binst\b\.|\binst\b", re.I): "institute",
    re.compile(r"\bcoll\b\.|\bcoll\b", re.I): "college",
    re.compile(r"\bsci\b\.|\bsci\b", re.I): "science",
    re.compile(r"\bnat\b\.", re.I): "national",
    re.compile(r"\bacad\b\.", re.I): "academy",
    re.compile(r"\bmed\b", re.I): "medical",
    re.compile(r"\bdept\b", re.I): "department",
    re.compile(r"\be-mail\b", re.I): "",
    re.compile(r"\bres\b\.", re.I): "research",
    re.compile(r"\bp\.o\. box\b", re.I): "",
    re.compile(r"\btelecom\b\.|\btelecommun\b", re.I): "telecommunications",
    re.compile(r"\badv\b\.", re.I): "advanced",
}

COUNTRY_REG = {
    "\\bAfghanistan\\b|\\bAFGHANISTAN\\b": "Afghanistan",
    "\\bAlbania\\b|\\bALBANIA\\b": "Albania",
    "\\bAlgeria\\b|\\bALGERIA\\b": "Algeria",
    "\\bAland Islands\\b|\\bALAND ISLANDS\\b": "Aland Islands",
    "\\bAmerican Samoa\\b|\\bAMERICAN SAMOA\\b|\\bAZ\\b|\\bCA\\b|\\bCO\\b|\\bGA\\b|\\bDE\\b|\\bGeorgia\\b|\\bGEORGIA\\b|\\bGuam\\b|\\bGUAM\\b|\\bGU\\b|\\bIL\\b|\\bIN\\b|\\bKY\\b|\\bLA\\b|\\bMO\\b|\\bMT\\b|\\bMA\\b|\\bMD\\b|\\bMN\\b|\\bNorthern Mariana Islands\\b|\\bMP\\b|\\bMS\\b|\\bNC\\b|\\bNE\\b|\\bPA\\b|\\bPuerto Rico\\b|\\bPUERTO RICO\\b|\\bPR\\b|\\bSC\\b|\\bSD\\b|\\bTN\\b|\\bUnited States\\b|\\bUNITED STATES\\b|\\bUS\\b|\\bUSA\\b|\\bU\\.S\\.\\b|\\bU\\.S\\.A\\b|\\bUnited states\\b|\\bUnited States of America\\b|\\bVA\\b|\\bVI\\b|\\bALABAMA\\b|\\bAlabama\\b|\\bALASKA\\b|\\bAlaska\\b|\\bAK\\b|\\bARIZONA\\b|\\bArizona\\b|\\bARKANSAS\\b|\\bArkansas\\b|\\bCALIFORNIA\\b|\\bCalifornia\\b|\\bCOLORADO\\b|\\bColorado\\b|\\bCONNECTICUT\\b|\\bConnecticut\\b|\\bCT\\b|\\bDELAWARE\\b|\\bDelaware\\b|\\bDISTRICT OF COLUMBIA\\b|\\bDistrict of Columbia\\b|\\bDC\\b|\\bFLORIDA\\b|\\bFlorida\\b|\\bFL\\b|\\bHAWAII\\b|\\bHawaii\\b|\\bHI\\b|\\bIDAHO\\b|\\bIdaho\\b|\\bILLINOIS\\b|\\bIllinois\\b|\\bINDIANA\\b|\\bIndiana\\b|\\bIOWA\\b|\\bIowa\\b|\\bIA\\b|\\bKANSAS\\b|\\bKansas\\b|\\bKS\\b|\\bKENTUCKY\\b|\\bKentucky\\b|\\bLOUISIANA\\b|\\bLouisiana\\b|\\bMAINE\\b|\\bMaine\\b|\\bME\\b|\\bMARYLAND\\b|\\bMaryland\\b|\\bMASSACHUSETTS\\b|\\bMassachusetts\\b|\\bMICHIGAN\\b|\\bMichigan\\b|\\bMI\\b|\\bMINNESOTA\\b|\\bMinnesota\\b|\\bMISSISSIPPI\\b|\\bMississippi\\b|\\bMISSOURI\\b|\\bMissouri\\b|\\bMONTANA\\b|\\bMontana\\b|\\bNEBRASKA\\b|\\bNebraska\\b|\\bNEVADA\\b|\\bNevada\\b|\\bNV\\b|\\bNEW HAMPSHIRE\\b|\\bNew Hampshire\\b|\\bNH\\b|\\bNEW JERSEY\\b|\\bNew Jersey\\b|\\bNJ\\b|\\bNEW MEXICO\\b|\\bNew Mexico\\b|\\bNM\\b|\\bNEW YORK\\b|\\bNew York\\b|\\bNY\\b|\\bNORTH CAROLINA\\b|\\bNorth Carolina\\b|\\bNORTH DAKOTA\\b|\\bNorth Dakota\\b|\\bND\\b|\\bNORTHERN MARIANA IS\\b|\\bOHIO\\b|\\bOhio\\b|\\bOH\\b|\\bOKLAHOMA\\b|\\bOklahoma\\b|\\bOK\\b|\\bOREGON\\b|\\bOregon\\b|\\bOR\\b|\\bPENNSYLVANIA\\b|\\bPennsylvania\\b|\\bRHODE\u00a0ISLAND\\b|\\bRhode\u00a0Island\\b|\\bRI\\b|\\bSOUTH CAROLINA\\b|\\bSouth Carolina\\b|\\bSOUTH DAKOTA\\b|\\bSouth Dakota\\b|\\bTENNESSEE\\b|\\bTennessee\\b|\\bTEXAS\\b|\\bTexas\\b|\\bTX\\b|\\bTex\\b|\\bUTAH\\b|\\bUtah\\b|\\bUT\\b|\\bVERMONT\\b|\\bVermont\\b|\\bVT\\b|\\bVIRGINIA\\b|\\bVirginia\\b|\\bVIRGIN ISLANDS\\b|\\bVirgin Islands\\b|\\bWASHINGTON\\b|\\bWashington\\b|\\bWA\\b|\\bWEST VIRGINIA\\b|\\bWest Virginia\\b|\\bWV\\b|\\bWISCONSIN\\b|\\bWisconsin\\b|\\bWI\\b|\\bWYOMING\\b|\\bWyoming\\b|\\bWY\\b|\\bSan Francisco\\b|\\bRhode Island\\b|\\bHarvard\\b|\\bStanford\\b|\\bYale\\b": "United States",
    "\\bAndorra\\b|\\bANDORRA\\b": "Andorra",
    "\\bAngola\\b|\\bANGOLA\\b": "Angola",
    "\\bAntigua and Barbuda\\b|\\bANTIGUA AND BARBUDA\\b": "Antigua and Barbuda",
    "\\bArgentina\\b|\\bARGENTINA\\b": "Argentina",
    "\\bArmenia\\b|\\bARMENIA\\b": "Armenia",
    "\\bAustralia\\b|\\bAUSTRALIA\\b|\\bSydney\\b|\\bACT\\b|\\bNSW\\b|\\bQLD\\b|\\bMonash\\b|\\bMelbourne\\b|\\bQueensland\\b": "Australia",
    "\\bAustria\\b|\\bAUSTRIA\\b|\\b\u00d6sterreich\\b": "Austria",
    "\\bAruba\\b|\\bARUBA\\b": "Aruba",
    "\\bAzerbaijan\\b|\\bAZERBAIJAN\\b": "Azerbaijan",
    "\\bBosnia and Herzegovina\\b|\\bBOSNIA AND HERZEGOVINA\\b|\\bBosnia\u2013Herzegovina\\b|\\bBosnia\\b": "Bosnia and Herzegovina",
    "\\bBarbados\\b|\\bBARBADOS\\b": "Barbados",
    "\\bBangladesh\\b|\\bBANGLADESH\\b": "Bangladesh",
    "\\bBelgium\\b|\\bBELGIUM\\b": "Belgium",
    "\\bBurkina Faso\\b|\\bBURKINA FASO\\b": "Burkina Faso",
    "\\bBulgaria\\b|\\bBULGARIA\\b": "Bulgaria",
    "\\bBahrain\\b|\\bBAHRAIN\\b": "Bahrain",
    "\\bBurundi\\b|\\bBURUNDI\\b": "Burundi",
    "\\bBenin\\b|\\bBENIN\\b": "Benin",
    "\\bBermuda\\b|\\bBERMUDA\\b": "Bermuda",
    "\\bBolivia\\b|\\bBOLIVIA\\b": "Bolivia",
    "\\bBrazil\\b|\\bBRAZIL\\b|\\bBrasil\\b": "Brazil",
    "\\bBahamas\\b|\\bBAHAMAS\\b": "Bahamas",
    "\\bBhutan\\b|\\bBHUTAN\\b": "Bhutan",
    "\\bBotswana\\b|\\bBOTSWANA\\b": "Botswana",
    "\\bBelarus\\b|\\bBELARUS\\b": "Belarus",
    "\\bBelize\\b|\\bBELIZE\\b": "Belize",
    "\\bCambodia\\b|\\bCAMBODIA\\b": "Cambodia",
    "\\bCameroon\\b|\\bCAMEROON\\b|\\bCM\\b": "Cameroon",
    "\\bCanada\\b|\\bCANADA\\b|\\bToronto\\b|\\bOntario\\b|\\bON\\b|\\bEdmonton\\b|\\bAB\\b|\\bQC\\b|\\bBC\\b|\\bQuebec\\b|\\bAlberta\\b": "Canada",
    "\\bCentral African Republic\\b|\\bCENTRAL AFRICAN REPUBLIC\\b": "Central African Republic",
    "\\bChad\\b|\\bCHAD\\b": "Chad",
    "\\bChile\\b|\\bCHILE\\b|\\bCL\\b": "Chile",
    "\\bChina\\b|\\bCHINA\\b|\\bCN\\b|\\bPeople's Republic of China\\b|\\bP\\.R\\. China\\b|\\bThe People's Republic of China\\b|\\bChinese\\b|\\bP\\.R\\.C\\b|\\bGuizhou\\b|\\bNanchang\\b|\\bHong Kong\\b|\\bPeking\\b|\\bHong Kong SAR\\b|\\bP\\. R\\. China\\b|\\bMacau\\b|\\bShanghai\\b|\\bWuhan\\b|\\bChangsha\\b|\\bBeijing\\b|\\bHONG KONG\\b|\\bHK\\b": "China",
    "\\bColombia\\b|\\bCOLOMBIA\\b": "Colombia",
    "\\bCook Islands\\b|\\bCOOK ISLANDS\\b|\\bCK\\b": "Cook Islands",
    "\\bCosta Rica\\b|\\bCOSTA RICA\\b": "Costa Rica",
    "\\bCroatia\\b|\\bCROATIA\\b|\\bHrvatska\\b": "Croatia",
    "\\bCuba\\b|\\bCUBA\\b": "Cuba",
    "\\bCyprus\\b|\\bCYPRUS\\b|\\bCY\\b": "Cyprus",
    "\\bDemocratic Republic of the Congo\\b|\\bDemocratic REPUBLIC of the Congo\\b|\\bCD\\b": "Democratic Republic of the Congo",
    "\\bDjibouti\\b|\\bDJIBOUTI\\b": "Djibouti",
    "\\bDenmark\\b|\\bDENMARK\\b|\\bCopenhagen\\b": "Denmark",
    "\\bDominica\\b|\\bDOMINICA\\b|\\bDM\\b": "Dominica",
    "\\bDominican Republic\\b|\\bDOMINICAN REPUBLIC\\b|\\bDO\\b": "Dominican Republic",
    "\\bEcuador\\b|\\bECUADOR\\b|\\bEC\\b": "Ecuador",
    "\\bEgypt\\b|\\bEGYPT\\b|\\bEG\\b": "Egypt",
    "\\bEl Salvador\\b|\\bEL SALVADOR\\b|\\bSV\\b": "El Salvador",
    "\\bEstonia\\b|\\bESTONIA\\b|\\bEE\\b": "Estonia",
    "\\bEquatorial Guinea\\b|\\bEQUATORIAL GUINEA\\b|\\bGQ\\b": "Equatorial Guinea",
    "\\bEritrea\\b|\\bERITREA\\b|\\bER\\b": "Eritrea",
    "\\bEthiopia\\b|\\bETHIOPIA\\b|\\bET\\b": "Ethiopia",
    "\\bFinland\\b|\\bFINLAND\\b|\\bFI\\b": "Finland",
    "\\bFiji\\b|\\bFIJI\\b|\\bFJ\\b": "Fiji",
    "\\bFaroe Islands\\b|\\bFAROE ISLANDS\\b|\\bFO\\b": "Faroe Islands",
    "\\bFrance\\b|\\bFRANCE\\b|\\bFR\\b|\\bParis\\b": "France",
    "\\bFrench Guiana\\b|\\bFRENCH GUIANA\\b|\\bGF\\b": "French Guiana",
    "\\bFrench Polynesia\\b|\\bFRENCH POLYNESIA\\b|\\bPF\\b": "French Polynesia",
    "\\bGabon\\b|\\bGABON\\b": "Gabon",
    "\\bGambia\\b|\\bGAMBIA\\b|\\bGM\\b": "Gambia",
    "\\bGermany\\b|\\bGERMANY\\b|\\bDeutschland\\b|\\bGerman\\b": "Germany",
    "\\bGhana\\b|\\bGHANA\\b|\\bGH\\b": "Ghana",
    "\\bGibraltar\\b|\\bGIBRALTAR\\b|\\bGI\\b": "Gibraltar",
    "\\bGrenada\\b|\\bGRENADA\\b|\\bGD\\b": "Grenada",
    "\\bGreece\\b|\\bGREECE\\b|\\bGR\\b": "Greece",
    "\\bGreenland\\b|\\bGREENLAND\\b|\\bGL\\b": "Greenland",
    "\\bGuinea\\b|\\bGUINEA\\b|\\bGN\\b": "Guinea",
    "\\bGuadeloupe\\b|\\bGUADELOUPE\\b|\\bGP\\b": "Guadeloupe",
    "\\bGuatemala\\b|\\bGUATEMALA\\b|\\bGT\\b": "Guatemala",
    "\\bGuinea-Bissau\\b|\\bGUINEA-BISSAU\\b|\\bGW\\b": "Guinea-Bissau",
    "\\bGuyana\\b|\\bGUYANA\\b|\\bGY\\b": "Guyana",
    "\\bHonduras\\b|\\bHONDURAS\\b|\\bHN\\b": "Honduras",
    "\\bHaiti\\b|\\bHAITI\\b|\\bHT\\b": "Haiti",
    "\\bHungary\\b|\\bHUNGARY\\b|\\bHU\\b|\\bBudapest\\b": "Hungary",
    "\\bIceland\\b|\\bICELAND\\b|\\bISL\\b": "Iceland",
    "\\bIndonesia\\b|\\bINDONESIA\\b": "Indonesia",
    "\\bIreland\\b|\\bIRELAND\\b": "Ireland",
    "\\bIsrael\\b|\\bISRAEL\\b": "Israel",
    "\\bIndia\\b|\\bINDIA\\b|\\bNew Delhi\\b": "India",
    "\\bIraq\\b|\\bIRAQ\\b|\\bIQ\\b": "Iraq",
    "\\bIran\\b|\\bIRAN\\b|\\bIR\\b|\\biran\\b": "Iran",
    "\\bItaly\\b|\\bITALY\\b|\\bItalia\\b|\\bParma\\b|\\bNaples\\b|\\bRome\\b": "Italy",
    "\\bJamaica\\b|\\bJAMAICA\\b|\\bJM\\b": "Jamaica",
    "\\bJordan\\b|\\bJORDAN\\b|\\bJO\\b": "Jordan",
    "\\bJapan\\b|\\bJAPAN\\b|\\bJP\\b|\\bTokyo\\b|\\bOsaka\\b|\\bKyoto\\b|\\bSendai\\b|\\bOkayama\\b|\\bKagawa\\b": "Japan",
    "\\bKenya\\b|\\bKENYA\\b|\\bKE\\b": "Kenya",
    "\\bKyrgyzstan\\b|\\bKYRGYZSTAN\\b|\\bKG\\b": "Kyrgyzstan",
    "\\bKiribati\\b|\\bKIRIBATI\\b|\\bKI\\b": "Kiribati",
    "\\bSaint Kitts and Nevis\\b|\\bSAINT KITTS AND NEVIS\\b|\\bKN\\b": "Saint Kitts and Nevis",
    "\\bSouth Korea\\b|\\bKOREA (SOUTH)\\b|\\bKR\\b|\\bKorea\\b|\\bRepublic of Korea\\b|\\bYonsei\\b|\\bSeoul\\b|\\bCoreia\\b": "South Korea",
    "\\bKuwait\\b|\\bKUWAIT\\b|\\bKW\\b": "Kuwait",
    "\\bCayman Islands\\b|\\bCAYMAN ISLANDS\\b": "Cayman Islands",
    "\\bKazakhstan\\b|\\bKAZAKHSTAN\\b|\\bKZ\\b": "Kazakhstan",
    "\\bLaos\\b|\\bLAOS\\b": "Laos",
    "\\bLebanon\\b|\\bLEBANON\\b|\\bLB\\b": "Lebanon",
    "\\bSaint Lucia\\b|\\bSAINT LUCIA\\b|\\bLC\\b": "Saint Lucia",
    "\\bLiechtenstein\\b|\\bLIECHTENSTEIN\\b|\\bLI\\b": "Liechtenstein",
    "\\bSri Lanka\\b|\\bSRI LANKA\\b|\\bLK\\b": "Sri Lanka",
    "\\bLiberia\\b|\\bLIBERIA\\b|\\bLR\\b": "Liberia",
    "\\bLesotho\\b|\\bLESOTHO\\b|\\bLS\\b": "Lesotho",
    "\\bLithuania\\b|\\bLITHUANIA\\b|\\bLT\\b": "Lithuania",
    "\\bLuxembourg\\b|\\bLUXEMBOURG\\b|\\bLU\\b": "Luxembourg",
    "\\bLatvia\\b|\\bLATVIA\\b|\\bLV\\b": "Latvia",
    "\\bLibya\\b|\\bLIBYA\\b|\\bLY\\b": "Libya",
    "\\bMadagascar\\b|\\bMADAGASCAR\\b|\\bMG\\b": "Madagascar",
    "\\bMalaysia\\b|\\bMALAYSIA\\b|\\bMY\\b": "Malaysia",
    "\\bMali\\b|\\bMALI\\b|\\bML\\b": "Mali",
    "\\bMalawi\\b|\\bMALAWI\\b|\\bMW\\b": "Malawi",
    "\\bMauritania\\b|\\bMAURITANIA\\b|\\bMR\\b": "Mauritania",
    "\\bMartinique\\b|\\bMARTINIQUE\\b|\\bMQ\\b": "Martinique",
    "\\bMauritius\\b|\\bMAURITIUS\\b|\\bMU\\b": "Mauritius",
    "\\bMalta\\b|\\bMALTA\\b": "Malta",
    "\\bMexico\\b|\\bMEXICO\\b|\\bMX\\b|\\bM\u00e9xico\\b": "Mexico",
    "\\bMorocco\\b|\\bMOROCCO\\b|\\bMaroc\\b": "Morocco",
    "\\bMonaco\\b|\\bMONACO\\b|\\bMC\\b": "Monaco",
    "\\bMoldova\\b|\\bMOLDOVA\\b": "Moldova",
    "\\bMongolia\\b|\\bMONGOLIA\\b": "Mongolia",
    "\\bMyanmar\\b|\\bMYANMAR\\b|\\bMM\\b": "Myanmar",
    "\\bMontserrat\\b|\\bMONTSERRAT\\b": "Montserrat",
    "\\bMaldives\\b|\\bMALDIVES\\b|\\bMV\\b": "Maldives",
    "\\bMozambique\\b|\\bMOZAMBIQUE\\b|\\bMZ\\b": "Mozambique",
    "\\bNamibia\\b|\\bNAMIBIA\\b": "Namibia",
    "\\bNew Caledonia\\b|\\bNEW CALEDONIA\\b": "New Caledonia",
    "\\bNiger\\b|\\bNIGER\\b": "Niger",
    "\\bNigeria\\b|\\bNIGERIA\\b|\\bNG\\b": "Nigeria",
    "\\bNicaragua\\b|\\bNICARAGUA\\b|\\bNI\\b": "Nicaragua",
    "\\bNetherlands\\b|\\bNETHERLANDS\\b|\\bNL\\b|\\bAmsterdam\\b": "Netherlands",
    "\\bNorway\\b|\\bNORWAY\\b|\\bNO\\b|\\bOslo\\b": "Norway",
    "\\bNepal\\b|\\bNEPAL\\b|\\bNP\\b": "Nepal",
    "\\bNiue\\b|\\bNIUE\\b|\\bNU\\b": "Niue",
    "\\bNew Zealand\\b|\\bNEW ZEALAND\\b|\\bNZ\\b|\\bAotearoa\\b": "New Zealand",
    "\\bOman\\b|\\bOMAN\\b|\\bOM\\b": "Oman",
    "\\bPanama\\b|\\bPANAMA\\b": "Panama",
    "\\bPeru\\b|\\bPERU\\b|\\bPE\\b|\\bPer\u00fa\\b": "Peru",
    "\\bPapua New Guinea\\b|\\bPAPUA NEW GUINEA\\b|\\bPG\\b": "Papua New Guinea",
    "\\bPhilippines\\b|\\bPHILIPPINES\\b|\\bPH\\b": "Philippines",
    "\\bPakistan\\b|\\bPAKISTAN\\b|\\bPK\\b": "Pakistan",
    "\\bPoland\\b|\\bPOLAND\\b|\\bPL\\b": "Poland",
    "\\bPalestinian Territory\\b|\\bPALESTINIAN TERRITORY\\b|\\bPS\\b": "Palestinian Territory",
    "\\bPortugal\\b|\\bPORTUGAL\\b|\\bPT\\b": "Portugal",
    "\\bPalau\\b|\\bPALAU\\b|\\bPW\\b": "Palau",
    "\\bParaguay\\b|\\bPARAGUAY\\b|\\bPY\\b": "Paraguay",
    "\\bQatar\\b|\\bQATAR\\b|\\bQA\\b": "Qatar",
    "\\bReunion\\b|\\bREUNION\\b|\\bRE\\b": "Reunion",
    "\\bRomania\\b|\\bROMANIA\\b|\\bRO\\b": "Romania",
    "\\bRussian Federation\\b|\\bRUSSIA\\b|\\bRUSSIAN FEDERATION\\b|\\bRU\\b|\\bRussia\\b|\\bRussian\\b|\\bbrussian\\b": "Russia",
    "\\bRwanda\\b|\\bRWANDA\\b|\\bRW\\b": "Rwanda",
    "\\bSaudi Arabia\\b|\\bSAUDI ARABIA\\b|\\bSA\\b|\\bSaudiArabia\\b|\\bSaudia Arabia\\b": "Saudi Arabia",
    "\\bSamoa\\b|\\bSAMOA\\b|\\bWS\\b": "Samoa",
    "\\bSaint Vincent and the Grenadines\\b|\\bSAINT VINCENT AND THE GRENADINES\\b|\\bVC\\b": "Saint Vincent and the Grenadines",
    "\\bSan Marino\\b|\\bSAN MARINO\\b|\\bSM\\b": "San Marino",
    "\\bSao Tome and Principe\\b|\\bSAO TOME AND PRINCIPE\\b|\\bST\\b": "Sao Tome and Principe",
    "\\bSerbia\\b|\\bSERBIA\\b": "Serbia",
    "\\bSenegal\\b|\\bSENEGAL\\b|\\bSN\\b": "Senegal",
    "\\bSeychelles\\b|\\bSEYCHELLES\\b": "Seychelles",
    "\\bSierra Leone\\b|\\bSIERRA LEONE\\b|\\bSL\\b": "Sierra Leone",
    "\\bSingapore\\b|\\bSINGAPORE\\b|\\bSG\\b": "Singapore",
    "\\bSlovakia\\b|\\bSLOVAKIA\\b|\\bSlovak Republic\\b": "Slovakia",
    "\\bSlovenia\\b|\\bSLOVENIA\\b|\\bSI\\b": "Slovenia",
    "\\bSolomon Islands\\b|\\bSOLOMON ISLANDS\\b|\\bSB\\b": "Solomon Islands",
    "\\bSomalia\\b|\\bSOMALIA\\b|\\bSO\\b": "Somalia",
    "\\bSouth Africa\\b|\\bSOUTH AFRICA\\b|\\bZA\\b": "South Africa",
    "\\bSpain\\b|\\bSPAIN\\b|\\bES\\b|\\bEspa\u00f1a\\b|\\bBarcelona\\b": "Spain",
    "\\bSudan\\b|\\bSUDAN\\b": "Sudan",
    "\\bSuriname\\b|\\bSURINAME\\b|\\bSR\\b": "Suriname",
    "\\bSvalbard and Jan Mayen\\b|\\bSVALBARD AND JAN MAYEN\\b|\\bSJ\\b": "Svalbard and Jan Mayen",
    "\\bSweden\\b|\\bSWEDEN\\b|\\bSE\\b": "Sweden",
    "\\bSwitzerland\\b|\\bSWITZERLAND\\b|\\bCH\\b|\\bBasel\\b": "Switzerland",
    "\\bSyria\\b|\\bSYRIA\\b|\\bSY\\b": "Syria",
    "\\bTaiwan\\b|\\bTAIWAN\\b|\\bTW\\b|\\bRepublic of China\\b|\\bROC\\b|\\bTainan\\b": "Taiwan",
    "\\bTanzania\\b|\\bTANZANIA\\b|\\bTZ\\b": "Tanzania",
    "\\bTajikistan\\b|\\bTAJIKISTAN\\b|\\bTJ\\b": "Tajikistan",
    "\\bThailand\\b|\\bTHAILAND\\b": "Thailand",
    "\\bTogo\\b|\\bTOGO\\b|\\bTG\\b": "Togo",
    "\\bTonga\\b|\\bTONGA\\b|\\bTO\\b": "Tonga",
    "\\bTrinidad and Tobago\\b|\\bTRINIDAD AND TOBAGO\\b|\\bTT\\b": "Trinidad and Tobago",
    "\\bTunisia\\b|\\bTUNISIA\\b": "Tunisia",
    "\\bTurkey\\b|\\bTURKEY\\b|\\bTR\\b|\\b\u0130stanbul\\b|\\bIstanbul\\b|\\bT\u00fcrkiye\\b": "Turkey",
    "\\bTurkmenistan\\b|\\bTURKMENISTAN\\b|\\bTM\\b": "Turkmenistan",
    "\\bTurks and Caicos Islands\\b|\\bTURKS AND CAICOS ISLANDS\\b|\\bTC\\b": "Turks and Caicos Islands",
    "\\bTuvalu\\b|\\bTUVALU\\b|\\bTV\\b": "Tuvalu",
    "\\bUkraine\\b|\\bUKRAINE\\b|\\bUA\\b": "Ukraine",
    "\\bUganda\\b|\\bUGANDA\\b|\\bUG\\b": "Uganda",
    "\\bUnited Arab Emirates\\b|\\bUNITED ARAB EMIRATES\\b|\\bAE\\b": "United Arab Emirates",
    "\\bUnited Kingdom\\b|\\bUNITED KINGDOM\\b|\\bUK\\b|\\bUnited Kingdom of Great Britain and Northern Ireland\\b|\\bLondon\\b|\\bSouthampton\\b|\\bU\\.K\\b|\\bEngland\\b|\\bScotland\\b|\\bOxford\\b": "United Kingdom",
    "\\bUruguay\\b|\\bURUGUAY\\b|\\bUY\\b": "Uruguay",
    "\\bUzbekistan\\b|\\bUZBEKISTAN\\b|\\bUZ\\b": "Uzbekistan",
    "\\bVanuatu\\b|\\bVANUATU\\b|\\bVU\\b": "Vanuatu",
    "\\bVenezuela\\b|\\bVENEZUELA\\b|\\bVE\\b": "Venezuela",
    "\\bVietnam\\b|\\bVIETNAM\\b|\\bVN\\b|\\bViet Nam\\b": "Vietnam",
    "\\bWestern Sahara\\b|\\bWESTERN SAHARA\\b|\\bEH\\b": "Western Sahara",
    "\\bYemen\\b|\\bYEMEN\\b|\\bYE\\b": "Yemen",
    "\\bZambia\\b|\\bZAMBIA\\b|\\bZM\\b": "Zambia",
    "\\bZimbabwe\\b|\\bZIMBABWE\\b|\\bZW\\b": "Zimbabwe",
    "\\bCzech Republic\\b|\\bCzechia\\b": "Czechia"
}